language: generic
sudo: required
services:
 - docker

before_install:
 - docker build -t deconectat/docker-react -f Docerfile.dev .

script:
 - docker run -e CI=true deconectat/docker-react npm run test
